resume: 
pretrain: /path/to/checkpoint.pt
seed: 1024
data:
    dataset: k400
    modality: video
    num_segments: 32
    seg_length: 1       # no use
    batch_size: 32
    workers: 8
    num_classes: 400
    image_tmpl: 'img_{:05d}.jpg' # no used
    train_root: '/path/to/dataset'
    train_list: 'lists/k400/trainlist.txt' 
    val_root: '/path/to/dataset'
    val_list: '/path/to/val_list.txt'
    label_list: 'lists/k400/kinetics_400_labels.csv'
    input_size: 224
    random_shift: True
    output_path: /path/to/output
network:
    arch: ViT-B/16      #ViT-B/32 ViT-B/16
    init: True
    tm: False           # no use
    drop_out: 0.0 
    emb_dropout: 0.0
    sim_header: Transf  # [Transf, None] 'Transf'：6-layer temporal transformer  'None': mean temporal pooling
    interaction: DP     # [DP] 'DP': mean temporal pooling
    joint_st: False     # whether use joint space-time attention in the transformer (default: False)
    drop: 0      
    temporal_layer: 6
    num_experts: 4      
    sampling_rates: [2, 4, 8, 16]  # sampling rates for each expert
    readout_fuse_type: linear # mean or linear
solver:
    type: cosine
    epochs: 40
    start_epoch: 0
    epoch_offset: 0
    optim: adamw
    lr: 1.e-4
    lr_warmup_step: 10
    weight_decay: 0.2
    loss_type: CE
    evaluate: True     # only run evaluation
    clip_ratio: 0.06
    grad_accumulation_steps: 2
logging:
    print_freq: 10
    eval_freq: 1